rm -rf lib \
       ABOUT-NLS \
       intl \
       gnulib \
       autom4te.cache \
       po \
       src/revision.h \
       INSTALL \
       aclocal.m4 \
       ar-lib \
       compile \
       Makefile.in \
       syntax/Makefile.in \
       src/Makefile.in \
       doc/Makefile.in \
       config.cache \
       config.guess \
       config.h \
       config.h.in \
       config.log \
       config.rpath \
       config.status \
       config.sub \
       configure \
       depcomp \
       install-sh \
       missing \
       mkinstalldirs \
       stamp-h1 \
       snippet \
       doc/texinfo.tex \
       m4/Makefile.in \
       m4/.gitignore \
       m4/00gnulib.m4 \
       m4/__inline.m4 \
       m4/absolute-header.m4 \
       m4/alloca.m4 \
       m4/btowc.m4 \
       m4/builtin-expect.m4 \
       m4/chdir-long.m4 \
       m4/clock_time.m4 \
       m4/close.m4 \
       m4/closedir.m4 \
       m4/ctype_h.m4 \
       m4/d-type.m4 \
       m4/dirent_h.m4 \
       m4/dirfd.m4 \
       m4/double-slash-root.m4 \
       m4/dup2.m4 \
       m4/eealloc.m4 \
       m4/errno_h.m4 \
       m4/error.m4 \
       m4/exponentd.m4 \
       m4/exponentf.m4 \
       m4/exponentl.m4 \
       m4/extensions.m4 \
       m4/fchdir.m4 \
       m4/fcntl.m4 \
       m4/fcntl_h.m4 \
       m4/filenamecat.m4 \
       m4/flexmember.m4 \
       m4/float_h.m4 \
       m4/fnmatch.m4 \
       m4/fnmatch_h.m4 \
       m4/fpieee.m4 \
       m4/free.m4 \
       m4/frexp.m4 \
       m4/frexpl.m4 \
       m4/fstat.m4 \
       m4/fstatat.m4 \
       m4/futimens.m4 \
       m4/getcwd.m4 \
       m4/getdelim.m4 \
       m4/getdtablesize.m4 \
       m4/getline.m4 \
       m4/getlogin.m4 \
       m4/getlogin_r.m4 \
       m4/getopt.m4 \
       m4/getprogname.m4 \
       m4/getrandom.m4 \
       m4/gettime.m4 \
       m4/gettimeofday.m4 \
       m4/glob.m4 \
       m4/glob_h.m4 \
       m4/gnulib-common.m4 \
       m4/gnulib-comp.m4 \
       m4/gnulib-tool.m4 \
       m4/include_next.m4 \
       m4/intmax_t.m4 \
       m4/inttypes.m4 \
       m4/isblank.m4 \
       m4/isnand.m4 \
       m4/isnanf.m4 \
       m4/isnanl.m4 \
       m4/iswblank.m4 \
       m4/langinfo_h.m4 \
       m4/largefile.m4 \
       m4/ldexpl.m4 \
       m4/libunistring-base.m4 \
       m4/limits-h.m4 \
       m4/localcharset.m4 \
       m4/locale-fr.m4 \
       m4/locale-ja.m4 \
       m4/locale-zh.m4 \
       m4/locale_h.m4 \
       m4/localeconv.m4 \
       m4/lstat.m4 \
       m4/malloc.m4 \
       m4/malloca.m4 \
       m4/math_h.m4 \
       m4/mbrtowc.m4 \
       m4/mbsinit.m4 \
       m4/mbsrtowcs.m4 \
       m4/mbstate_t.m4 \
       m4/mbtowc.m4 \
       m4/memchr.m4 \
       m4/mempcpy.m4 \
       m4/memrchr.m4 \
       m4/minmax.m4 \
       m4/mkdir.m4 \
       m4/mkstemps.m4 \
       m4/mmap-anon.m4 \
       m4/mode_t.m4 \
       m4/msvc-inval.m4 \
       m4/msvc-nothrow.m4 \
       m4/multiarch.m4 \
       m4/nl_langinfo.m4 \
       m4/nocrash.m4 \
       m4/off_t.m4 \
       m4/open-cloexec.m4 \
       m4/open-slash.m4 \
       m4/open.m4 \
       m4/openat.m4 \
       m4/opendir.m4 \
       m4/pathmax.m4 \
       m4/pid_t.m4 \
       m4/pipe.m4 \
       m4/printf-frexp.m4 \
       m4/printf-frexpl.m4 \
       m4/printf.m4 \
       m4/pthread_rwlock_rdlock.m4 \
       m4/raise.m4 \
       m4/readdir.m4 \
       m4/realloc.m4 \
       m4/regex.m4 \
       m4/save-cwd.m4 \
       m4/setlocale_null.m4 \
       m4/sigaction.m4 \
       m4/signal_h.m4 \
       m4/signalblocking.m4 \
       m4/signbit.m4 \
       m4/snprintf-posix.m4 \
       m4/snprintf.m4 \
       m4/ssize_t.m4 \
       m4/stat-time.m4 \
       m4/stat.m4 \
       m4/std-gnu11.m4 \
       m4/stdalign.m4 \
       m4/stdarg.m4 \
       m4/stdbool.m4 \
       m4/stddef_h.m4 \
       m4/stdint.m4 \
       m4/stdio_h.m4 \
       m4/stdlib_h.m4 \
       m4/strcase.m4 \
       m4/strcasestr.m4 \
       m4/strdup.m4 \
       m4/strerror.m4 \
       m4/string_h.m4 \
       m4/strings_h.m4 \
       m4/strnlen.m4 \
       m4/sys_random_h.m4 \
       m4/sys_socket_h.m4 \
       m4/sys_stat_h.m4 \
       m4/sys_time_h.m4 \
       m4/sys_types_h.m4 \
       m4/sys_wait_h.m4 \
       m4/tempname.m4 \
       m4/time_h.m4 \
       m4/timespec.m4 \
       m4/unistd-safer.m4 \
       m4/unistd_h.m4 \
       m4/utime.m4 \
       m4/utime_h.m4 \
       m4/utimens.m4 \
       m4/utimes.m4 \
       m4/vararrays.m4 \
       m4/vasnprintf.m4 \
       m4/vsnprintf-posix.m4 \
       m4/vsnprintf.m4 \
       m4/warn-on-use.m4 \
       m4/wchar_h.m4 \
       m4/wcrtomb.m4 \
       m4/wctype_h.m4 \
       m4/wcwidth.m4 \
       m4/wmemchr.m4 \
       m4/wmempcpy.m4 \
       m4/year2038.m4 \
       m4/zzgnulib.m4 \
       m4/*.m4~
